# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gptcli < Formula
  desc "An interactive ChatGPT client featuring shortcuts and auto-complete."
  homepage "https://github.com/lucasepe/gptcli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucasepe/gptcli/releases/download/v0.1.0/gptcli_0.1.0_darwin_arm64.tar.gz"
      sha256 "43d62f15126384e29eeb4633c448acbc2482ea3a66dd3f347dbc387df0055e75"

      def install
        bin.install "gptcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/gptcli/releases/download/v0.1.0/gptcli_0.1.0_darwin_amd64.tar.gz"
      sha256 "5515007594874504fae6b75f0e18d44f0636bb769173d58bd3c35be4ab99bf7a"

      def install
        bin.install "gptcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasepe/gptcli/releases/download/v0.1.0/gptcli_0.1.0_linux_arm64.tar.gz"
      sha256 "cd1e6e591e03a460f202a2f20b0b67c1e75af1731d30d187435ecbf7e86f4f5c"

      def install
        bin.install "gptcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/gptcli/releases/download/v0.1.0/gptcli_0.1.0_linux_amd64.tar.gz"
      sha256 "c5addcbb8af8c4a27c18746498af89177c80fc8fe91c4eb1cd563a4189bfe32d"

      def install
        bin.install "gptcli"
      end
    end
  end
end
